---
title: Franck Dupont
timezone: Europe/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
highlighter: rouge
permalink: pretty
tagline: kindness and radicality
description: bienveillance & radicalit√©.
url: https://franckdupont.com/
baseurl: https://franckdupont.com/
author:
  name: Franck Dupont
paginate: 5
version: 2.1.0
